dusainet2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from article.views import ArticlePostView
from article.feeds import ArticlesPostRssFeed, ArticlesPostColumnRssFeed

import notifications.urls

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    url(r'^$', ArticlePostView.as_view(), name='home'),
    path('admiration/', TemplateView.as_view(template_name='admiration.html'), name='admiration'),

    path('userinfo/', include('userinfo.urls', namespace='userinfo')),

    path('article/', include('article.urls', namespace='article')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    path('album/', include('album.urls', namespace='album')),
    path('course/', include('course.urls', namespace='course')),

    path('book/', include('readbook.urls', namespace='readbook')),

    path('imagesource/', include('imagesource.urls', namespace='imagesource')),

    path('vlog/', include('vlog.urls', namespace='vlog')),

    path('aboutme/', include('aboutme.urls', namespace='aboutme')),

    path('my-notifications/', include('mynotifications.urls', namespace='my_notifications')),

    # RSS订阅
    url(r'^all/rss/$', ArticlesPostRssFeed(), name='rss'),
    path('all/rss/<int:column_id>/', ArticlesPostColumnRssFeed(), name='column_rss'),

    # haystack search
    url(r'^search/', include('haystack.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),

    # notifications
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest-framework login view
    url(r'^api/auth/', include('rest_framework.urls')),

    # api-article
    path('api/article/', include('article.api.urls', namespace='api_article')),

    # api-comments
    path('api/comments/', include('comments.api.urls', namespace='api_comments')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mynotifications/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'my_notifications'
urlpatterns = [
    path(
        '',
        views.comments_notification,
        name='notify_box',
    ),
    path(
        'mark-all-read',
        views.comments_notification_mark_all_as_read,
        name='mark_all_read',
    ),
    path(
        'mark-as-read/<int:article_id>/<int:notify_id>/<article_type>/',
         views.comments_notification_mark_as_read,
        name='mark_as_read',
    ),
]

vlog/urls.py
from django.urls import path
from . import views

app_name = 'vlog'

urlpatterns = [
    path('', views.VlogListView.as_view(), name='list'),
    path('detail/<int:pk>', views.VlogDetailView.as_view(), name='detail'),
]

mynotifications/models.py
from django.db import models

# Create your models here.

mynotifications/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from article.models import ArticlesPost
from readbook.models import ReadBook
from vlog.models import Vlog


@login_required(login_url='/accounts/weibo/login/?process=login')
def comments_notification(request):
    """
    通知界面
    """
    unread_notify = request.user.notifications.unread()
    return render(
        request,
        'notifications/my_notification.html',
        {'unread_notify': unread_notify},
    )


@login_required(login_url='/accounts/weibo/login/?process=login')
def comments_notification_mark_all_as_read(request):
    """
    标记所有信息为已读
    """
    request.user.notifications.mark_all_as_read()
    return redirect('my_notifications:notify_box')


@login_required(login_url='/accounts/weibo/login/?process=login')
def comments_notification_mark_as_read(request,
                                       article_id,
                                       notify_id,
                                       article_type):
    """
    标记点击过的信息为已读
    """
    if article_type == 'article':
        article = ArticlesPost.objects.get(id=article_id)

    elif article_type == 'readbook':
        article = ReadBook.objects.get(id=article_id)

    else:
        article = Vlog.objects.get(id=article_id)

    request.user.notifications.get(id=notify_id).mark_as_read()
    return redirect(article)

templates/notifications/my_notification.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load notifications_tags %}
{% block title %}通知列表 - 杜赛的个人网站{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mt-2">
            <div class="">
                <a class="btn btn-warning mb-2"
                   href="{% url 'my_notifications:mark_all_read' %}"
                >
                    标记全部已读
                </a>
                <div class="list-group list-group-flush" id="link_base">
                    {% for unread in unread_notify %}
                        <a id="my_link"
                           href="{% url 'my_notifications:mark_as_read' unread.target_object_id unread.id unread.description %}#F{{ unread.action_object.id }}"
                           target="_blank"
                           class="list-group-item list-group-item-action"
                        >
                        <span style="color: #5897fb;">
                            {{ unread.actor }}
                        </span>
                            {% if unread.actor.is_superuser %}
                                <span style="color: #FF5722">[博主]</span>
                            {% elif unread.actor.is_staff %}
                                <i style="color: #5897fb;">[管理员]</i>
                            {% endif %}
                            在 <span
                                style="color: #01a252;">《{{ unread.target }}》</span>
                            中回复了你。&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ unread.timestamp|date:"Y-m-d H:i:s" }}
                        </a>
                    {% endfor %}
                    <hr>
                </div>

            </div>
        </div>
    </div>

    <link rel="stylesheet" href="{% static 'mystyle.css' %}">
    <style>
        #link_base a:link {
            color: black;
        }

        #link_base a:visited {
            color: lightgrey;
        }
    </style>
{% endblock %}