aboutme/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'aboutme'
urlpatterns = [
    # 自我简介
    path(
        '',
        TemplateView.as_view(template_name='aboutme/footpoint.html'),
        name='footpoint'
    ),
]

album/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'album'
urlpatterns = [
    # 列表
    path('', views.AlbumListView.as_view(), name='album_list'),
    # 暂未使用的管理页面
    path('manage/', views.album_manage, name='album_manage'),
    path('upload/', views.AlbumUpload.as_view(), name='album_upload'),
    url(r'^delete/(?P<image_id>\d+)/$', views.album_delete, name='album_delete'),
]

article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'
urlpatterns = [
    # 文章列表
    url(r'^list/$', views.ArticlePostView.as_view(), name='article_list'),

    # 文章内容
    url(
        r'^detail/(?P<article_id>\d+)/$',
        views.article_detail,
        name='article_detail',
    ),

    # 写新文章
    url(
        r'^create/$',
        views.ArticleCreateView.as_view(),
        name='article_create',
    ),

    # 更新文章
    url(
        r'update/(?P<pk>\d+)/$',
        views.ArticleUpdateView.as_view(),
        name='article_update',
    ),
]

course/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'course'
urlpatterns = [
    path(
        '',
        views.CourseListView.as_view(),
        name='course_list',
    ),
    url(
        r'^articles-list/(?P<course_id>\d+)/$',
        views.course_articles_list,
        name='course_articles_list',
    ),
]

dusainet2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from article.views import ArticlePostView
from article.feeds import ArticlesPostRssFeed, ArticlesPostColumnRssFeed

import notifications.urls

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    url(r'^$', ArticlePostView.as_view(), name='home'),
    path('admiration/', TemplateView.as_view(template_name='admiration.html'), name='admiration'),

    path('userinfo/', include('userinfo.urls', namespace='userinfo')),

    path('article/', include('article.urls', namespace='article')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    path('album/', include('album.urls', namespace='album')),
    path('course/', include('course.urls', namespace='course')),

    path('book/', include('readbook.urls', namespace='readbook')),

    path('imagesource/', include('imagesource.urls', namespace='imagesource')),

    path('vlog/', include('vlog.urls', namespace='vlog')),

    path('aboutme/', include('aboutme.urls', namespace='aboutme')),

    path('my-notifications/', include('mynotifications.urls', namespace='my_notifications')),

    # RSS订阅
    url(r'^all/rss/$', ArticlesPostRssFeed(), name='rss'),
    path('all/rss/<int:column_id>/', ArticlesPostColumnRssFeed(), name='column_rss'),

    # haystack search
    url(r'^search/', include('haystack.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),

    # notifications
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest-framework login view
    url(r'^api/auth/', include('rest_framework.urls')),

    # api-article
    path('api/article/', include('article.api.urls', namespace='api_article')),

    # api-comments
    path('api/comments/', include('comments.api.urls', namespace='api_comments')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vlog/urls.py
from django.urls import path
from . import views

app_name = 'vlog'

urlpatterns = [
    path('', views.VlogListView.as_view(), name='list'),
    path('detail/<int:pk>', views.VlogDetailView.as_view(), name='detail'),
]

templates/admiration.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}赞赏 - 杜赛的个人网站{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">
    <div class="container">
        <div class="">
            <h3 class="alert alert-success mt-4">小额赞赏</h3>

            <div class="row mb-4">
                <h5 class="text-muted mb-4 col-12" style="text-align: center">
                    感谢你的鼓励，我会继续努力写出高质量文章
                </h5>
                <div style="text-align: center" class="col">
                    <h3>微信赞赏码</h3>
                    <img src="{% static 'img/zanshangma.jpeg' %}" style="max-width: 300px">
                </div>
                <div style="text-align: center" class="col">
                    <h3>支付宝赞赏码</h3>
                    <img src="{% static 'img/zhifubao.jpeg' %}" style="max-width: 300px">
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
{% endblock %}

templates/back_top_func.html
<!-- Author: 鹦鹉 -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 10;"></button>
<script>
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 333);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(222);
            } else {
                $('#BackTop').stop().fadeOut(222);
            }
        }).scroll();
    });
</script>

<style>
    /* 56px */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="bookmark" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous"
    >
    <link rel="stylesheet" href="{% static 'monokai.css' %}">
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123957004-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-123957004-1');
    </script>


    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?f1ad3aa5133d41495a918468cab623d4";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>

</head>
<body>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.14.7/esm/popper.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static 'layer/layer.js' %}"></script>

{% include "back_top_func.html" %}
{% include "header.html" %}
<div id="wrapper">
    {% block content %}{% endblock %}
    <div id="push"></div>
</div>
{% include "footer.html" %}


{% block script %}{% endblock %}

</body>
</html>

templates/base_with_rslider.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <link rel="bookmark" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous"
    >

    <link rel="stylesheet" href="{% static 'monokai.css' %}">
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123957004-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-123957004-1');
    </script>


    <script>
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?f1ad3aa5133d41495a918468cab623d4";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>

</head>
<body>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/popper.js/1.14.7/esm/popper.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static 'layer/layer.js' %}"></script>


{% include "back_top_func.html" %}
{% include "header.html" %}
<div class="container" id="wrapper">
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
        <div class="col-3 d-none d-lg-block">
            {% include 'rightslider.html' %}
        </div>
    </div>
    <div id="push"></div>
</div>
{% include "footer.html" %}

{% block script %}{% endblock %}
</body>
</html>

templates/footer.html
{% load staticfiles %}
<nav class="navbar navbar-dark bg-dark mb-0" id="nav-footer">
    <div class="row col justify-content-center">
        <h3 class="mr-3 ml-4">
            <a href="mailto:dusaiphoto@foxmail.com">
                <i class="fas fa-envelope" style="color: lightskyblue;" id="layer_email"></i>
            </a>
        </h3>
        <h3 class="mr-3">
            <a href="https://github.com/stacklens" style="color: #f0c674;" target="_blank">
                <i class="fab fa-github" id="layer_github"></i>
            </a>
        </h3>
        <h3>
            <a href="//weibo.com/saisaixuezhang" style="color: indianred;" target="_blank">
                <i class="fab fa-weibo" id="layer_weibo"></i>
            </a>
        </h3>
    </div>

    <div class="row col-12 justify-content-center">
        <div style="text-align: center; color: lightgrey;">
            <p class="mb-0">CopyRight &copy; 2018 ~ 2019 杜赛的个人网站</p>
            <p class="mb-0">Powered by
                <a href="https://www.djangoproject.com/" target="_blank">
                    Django
                </a> &
                <a target="_blank" href="https://getbootstrap.com/">
                    Bootstrap
                </a>
                <span class="mb-0">&nbsp;蜀ICP备18018263号-1</span>
            </p>
        </div>
    </div>
</nav>
<script>
    $('#layer_email').on('mouseenter', function () {
        this.index = layer.tips('给作者发邮件', this, {
            time: -1,
            maxWidth: 280,
            tips: [1, 'lightskyblue']
        });
    }).on('mouseleave', function () {
        layer.close(this.index);
    });

    $('#layer_weibo').on('mouseenter', function () {
        this.index = layer.tips('关注作者微博', this, {
            time: -1,
            maxWidth: 280,
            tips: [1, 'indianred']
        });
    }).on('mouseleave', function () {
        layer.close(this.index);
    });

    $('#layer_github').on('mouseenter', function () {
        this.index = layer.tips('在GitHub查看作者代码', this, {
            time: -1,
            maxWidth: 280,
            tips: [1, '#f0c674']
        });
    }).on('mouseleave', function () {
        layer.close(this.index);
    });
</script>

templates/header.html
{% load staticfiles %}
{% load notifications_tags %}
{% load weibo_utils %}
{% load get_userinfo %}
{% get_userinfo user.id as userinfo %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- 导航 -->
    <a class="navbar-brand" href="/" style="font-size: 1.2em;">
        杜赛的个人网站
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        {% if unread_count %}
            <svg xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 8 42"
                 width="8px"
                 height="42px">
                <circle cx="4"
                        cy="4"
                        r="4"
                        fill="#ff6b6b"
                        fill-opacity="1.0"
                ></circle>
            </svg>
        {% endif %}
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="
                nav-item
                {% if 'article' in request.path or request.path == '/' %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="/">
                    文章
                </a>
            </li>
            <li class="
                nav-item
                {% if '/course' in request.path %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="{% url 'course:course_list' %}">
                    教程
                </a>
            </li>
            <li class="
                nav-item
                {% if '/book' in request.path %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="{% url 'readbook:book_list' %}">
                    知识
                </a>
            </li>
            <li class="
                nav-item
                {% if '/album' in request.path %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="{% url 'album:album_list' %}">
                    照片墙
                </a>
            </li>
            <li class="
                nav-item
                {% if '/vlog' in request.path %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="{% url 'vlog:list' %}">
                    视频
                </a>
            </li>
            <li class="
                nav-item
                {% if '/aboutme' in request.path %}
                active
                {% endif %}
                "
            >
                <a class="nav-link mr-2" href="{% url 'aboutme:footpoint' %}">
                    关于
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-md-auto" style="margin: -5px 0 -5px 0;">

            <!-- 搜索框 -->
            <form role="search"
                  class="form-inline my-2 my-lg-0"
                  method="get"
                  id="searchform"
                  action="{% url 'haystack_search' %}"
            >
                <input style=" background-color: #dddddd"
                       type="search"
                       aria-label="Search"
                       name="q"
                       placeholder="搜索文章.."
                       required
                       class="form-control mr-sm-2"
                >
            </form>


            <!-- 用户下拉条avatar -->
            {% if user.is_authenticated %}
                <li class="nav-item dropdown" style="float: right;">
                    {% if user.socialaccount_set.all.0.get_avatar_url %}
                        <a class="nav-link dropdown-toggle"
                           id="navbarDropdownMenuLink"
                           role="button"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false"
                           href="#"
                        >
                            {% if unread_count %}
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 8 42"
                                     width="8px"
                                     height="42px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                            fill-opacity="1.0"
                                    ></circle>
                                </svg>
                            {% endif %}
                            <img src="{% translate_avatar_ssl user.socialaccount_set.all.0.get_avatar_url %}"
                                 style="max-height: 40px; border-radius: 20%"
                                 alt="头像"
                            >
                        </a>
                    {% elif userinfo.avatar %}
                        {% if 'static' in userinfo.avatar.url %}
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdownMenuLink"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false"
                               href="#"
                            >
                                {% if unread_count %}
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 8 42"
                                         width="8px"
                                         height="42px">
                                        <circle cx="4"
                                                cy="4"
                                                r="4"
                                                fill="#ff6b6b"
                                                fill-opacity="1.0"
                                        ></circle>
                                    </svg>
                                {% endif %}
                                <img src="{{ userinfo.avatar }}"
                                     alt="avatar"
                                     style="max-height: 40px; border-radius: 20%"
                                >
                            </a>
                        {% else %}
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdownMenuLink"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false"
                               href="#"
                               style="color: gray;"
                            >
                                {% if unread_count %}
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 8 42"
                                         width="8px"
                                         height="42px">
                                        <circle cx="4"
                                                cy="4"
                                                r="4"
                                                fill="#ff6b6b"
                                                fill-opacity="1.0"
                                        ></circle>
                                    </svg>
                                {% endif %}
                                <img src="{{ userinfo.avatar.url }}"
                                     alt="avatar"
                                     style="max-height: 40px; border-radius: 20%"
                                >
                            </a>
                        {% endif %}
                    {% else %}
                        <a class="nav-link dropdown-toggle"
                           id="navbarDropdownMenuLink"
                           role="button"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false"
                           href="#"
                           style="color: gray;"
                        >
                            {% if unread_count %}
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     viewBox="0 0 8 42"
                                     width="8px"
                                     height="42px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                            fill-opacity="1.0"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                    {% endif %}


                    <!-- 用户下拉条item -->
                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="navbarDropdownMenuLink"
                    >
                        <a href="{% url 'my_notifications:notify_box' %}"
                           class="dropdown-item"
                        >
                            通知
                            {% if unread_count %}
                                <span class="badge badge-danger">
                                    {{ unread_count }}
                                </span>
                            {% endif %}
                        </a>
                        <a href="{% url 'userinfo:detail' %}"
                           class="dropdown-item"
                        >
                            个人信息
                        </a>
                        {% if user.is_superuser %}
                            <a href="{% url 'article:article_create' %}" class="dropdown-item"
                            >
                                写文章
                            </a>
                            <a href="/admin" class="dropdown-item"
                            >
                                后台
                            </a>
                            <a href="{% url 'imagesource:imagesource_list' %}"
                               class="dropdown-item"
                            >
                                图库
                            </a>
                        {% endif %}
                        <a href="javascript:"
                           class="dropdown-item"
                           data-toggle="modal"
                           data-target="#logout"
                        >
                            退出登录
                        </a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item"
                >
                    <a href="{% url 'account_login' %}" class="nav-link">
                        登录
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>


    <div class="modal fade" id="logout" tabindex="-1" role="dialog" aria-labelledby="logout" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <h5 class="modal-body">
                    确认退出吗？
                </h5>
                <div class="modal-footer">
                    <form method="post" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">退出登录</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">返回</button>
                </div>
            </div>
        </div>
    </div>

</nav>

templates/license.html
<!-- 知识产权署名 -->
<div class="alert alert-secondary text-muted mt-4 mb-4">
    <div>
        <span>本文标题：
            <a href="https://www.dusaiphoto.com{{ request.path }}" style="color: gray;">
                {{ article.title }}
            </a>
        </span>
    </div>
    <div>
        <span>本文作者：
            <a href="https://www.dusaiphoto.com" style="color: gray;">
                杜赛
            </a>
        </span>
    </div>
    <div>
        <span>发布时间：
            {{ article.created|date:"Y年m月d日 - H:i" }}
        </span>
    </div>
    <div>
        <span>最后更新：
            {{ article.updated|date:"Y年m月d日 - H:i" }}
        </span>
    </div>
    <div>
        <span>
            原始链接：
            <a href="https://www.dusaiphoto.com{{ request.path }}"
               style="word-break: break-all; color: gray;"
            >
                https://www.dusaiphoto.com{{ request.path }}
            </a>
        </span>
    </div>
    <div>
        <span>
            许可协议：
            <a rel="license"
               href="https://creativecommons.org/licenses/by-nc/4.0/"
               target="_blank"
               style="color: gray;"
            >
                署名-非商业性使用 4.0 国际许可协议
            </a>
        </span>
    </div>
    <div style="margin-top: 6px">
        <a rel="license"
           href="https://creativecommons.org/licenses/by-nc/4.0/"
           target="_blank"
        >
            <img alt="知识共享许可协议"
                 style="border-width:0"
                 src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png"
                 title="知识共享署名/非商业性使用"
            />
        </a>
        <span>
            &nbsp;&nbsp;<u>转载请保留原文链接及作者</u>
        </span>
    </div>

</div>

templates/paginator.html
{% if is_paginated %}
    <div class="row justify-content-center" style="text-align: center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if first %}
                    <li class="page-item">
                        <a href="?page=1&order={{ order }}&column_id={{ column_id }}&tag={{ tag }}"
                           class="page-link"
                           role="button"
                        >
                            1
                        </a>
                    </li>

                {% endif %}
                {% if left %}
                    {% if left_has_more %}
                        <span class="ml-1 mr-1">...</span>
                    {% endif %}
                    {% for i in left %}
                        <li class="page-item">

                            <a href="?page={{ i }}&order={{ order }}&column_id={{ column_id }}&tag={{ tag }}"
                               class="page-link"
                            >
                                {{ i }}
                            </a>
                        </li>
                    {% endfor %}
                {% endif %}
            <li class="page-item active">

                <a href="?page={{ page_obj.number }}&order={{ order }}&column_id={{ column_id }}&tag={{ tag }}"
                   class="page-link"
                >
                    {{ page_obj.number }}
                </a>
            </li>
                {% if right %}
                    {% for i in right %}
                        <li class="page-item">

                            <a href="?page={{ i }}&order={{ order }}&column_id={{ column_id }}&tag={{ tag }}"
                               class="page-link"
                            >
                                {{ i }}
                            </a>
                        </li>
                    {% endfor %}
                    {% if right_has_more %}
                        <span class="ml-1 mr-1">...</span>
                    {% endif %}
                {% endif %}
                {% if last %}
                    <li class="page-item">

                        <a href="?page={{ paginator.num_pages }}&order={{ order }}&column_id={{ column_id }}&tag={{ tag }}"
                           class="page-link"
                        >
                            {{ paginator.num_pages }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    </div>

{% endif %}