comments/api/urls.py
from django.urls import path

from comments.api.views import (
CommentListAPIView,
CommentDetailAPIView,
CommentCreateAPIView,
)

app_name = 'comment'

urlpatterns = [
    path('create/', CommentCreateAPIView.as_view(), name='create'),
    path('<int:pk>/', CommentDetailAPIView.as_view(), name='detail'),
    path('list/', CommentListAPIView.as_view(), name='list'),
]

comments/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    # 发表一级回复
    path(
        'post-comment/<int:article_id>/',
        views.CommentCreateView.as_view(),
        name='post_comment'
    ),

    # 发表二级回复
    path(
        'reply-post-comment/<int:article_id>/<int:node_id>/<article_type>/',
        views.CommentCreateView.as_view(),
        name='reply_post_comment'
    ),

    # 软删除
    path(
        'soft-delete/',
        views.comment_soft_delete,
        name='soft_delete'
    ),

    # edit
    path(
        'edit/<int:pk>/',
        views.CommentUpdateView.as_view(),
        name='edit'
    )
]

dusainet2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from article.views import ArticlePostView
from article.feeds import ArticlesPostRssFeed, ArticlesPostColumnRssFeed

import notifications.urls

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    url(r'^$', ArticlePostView.as_view(), name='home'),
    path('admiration/', TemplateView.as_view(template_name='admiration.html'), name='admiration'),

    path('userinfo/', include('userinfo.urls', namespace='userinfo')),

    path('article/', include('article.urls', namespace='article')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    path('album/', include('album.urls', namespace='album')),
    path('course/', include('course.urls', namespace='course')),

    path('book/', include('readbook.urls', namespace='readbook')),

    path('imagesource/', include('imagesource.urls', namespace='imagesource')),

    path('vlog/', include('vlog.urls', namespace='vlog')),

    path('aboutme/', include('aboutme.urls', namespace='aboutme')),

    path('my-notifications/', include('mynotifications.urls', namespace='my_notifications')),

    # RSS订阅
    url(r'^all/rss/$', ArticlesPostRssFeed(), name='rss'),
    path('all/rss/<int:column_id>/', ArticlesPostColumnRssFeed(), name='column_rss'),

    # haystack search
    url(r'^search/', include('haystack.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),

    # notifications
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest-framework login view
    url(r'^api/auth/', include('rest_framework.urls')),

    # api-article
    path('api/article/', include('article.api.urls', namespace='api_article')),

    # api-comments
    path('api/comments/', include('comments.api.urls', namespace='api_comments')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vlog/urls.py
from django.urls import path
from . import views

app_name = 'vlog'

urlpatterns = [
    path('', views.VlogListView.as_view(), name='list'),
    path('detail/<int:pk>', views.VlogDetailView.as_view(), name='detail'),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from mptt.models import MPTTModel, TreeForeignKey

from ckeditor.fields import RichTextField


# 博文的评论
class Comment(MPTTModel):
    """
    评论
    GenericForeignkey
    """
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments_user',
        verbose_name='评论者',
    )

    body = RichTextField(verbose_name='正文')
    created_time = models.DateTimeField(auto_now_add=True)

    # 记录二级评论回复给谁, str
    reply_to = models.ForeignKey(
        User,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='comments_reply_to',
        verbose_name='评论给'
    )

    # mptt树形结构
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True, blank=True,
        related_name='children',
        verbose_name='父级',
    )

    # 软删除标记
    is_deleted = models.BooleanField(default=False)
    is_deleted_by_staff = models.BooleanField(default=False)

    class MPTTMeta:
        order_insertion_by = ['created_time']

    def __str__(self):
        return self.body[:20]

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

comments/api/views.py
from django.db.models import Q
from django.contrib.auth.models import User

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

from rest_framework.mixins import (
    DestroyModelMixin,
    UpdateModelMixin,
)

from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
)

from rest_framework.permissions import (
    IsAuthenticatedOrReadOnly,
    IsAdminUser,
)

from comments.models import Comment
from .serializers import (
    CommentListSerializer,
    CommentDetailSerializer,
    CommentCreateSerializer,
)

from article.models import ArticlesPost
from .permissions import IsOwnerOrReadOnly
from article.api.pagination import ArticlePageNumberPagination


# Create your views here.
# 增
class CommentCreateAPIView(CreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentCreateSerializer
    permission_classes = [IsAdminUser]

    def perform_create(self, serializer):
        serializer.save(
            article=ArticlesPost.objects.get(id=self.request.GET.get("article_id")),
            reply_to=User.objects.filter(id=self.request.GET.get("reply_to")).first(),
            parent=Comment.objects.filter(id=self.request.GET.get("parent")).first(),
            user=self.request.user,
        )


# 删改查
class CommentDetailAPIView(DestroyModelMixin, UpdateModelMixin, RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class CommentListAPIView(ListAPIView):
    serializer_class = CommentListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['body']
    pagination_class = ArticlePageNumberPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = Comment.objects.all()
        query = self.request.GET.get("q")

        if query:
            queryset_list = queryset_list.filter(
                Q(content__icontains=query)
            ).distinct()
        return queryset_list

comments/views.py
from django.shortcuts import (
    render,
    get_object_or_404,
    redirect,
)

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from notifications.signals import notify

from .models import Comment
from .forms import CommentForm

from article.models import ArticlesPost
from readbook.models import ReadBook
from vlog.models import Vlog

# from utils.utils import send_email_to_user

from django.views.generic import CreateView, UpdateView
from braces.views import LoginRequiredMixin


class CommentUpdateView(LoginRequiredMixin,
                        UpdateView):
    """
    更新回复
    """
    context_object_name = 'comment'
    template_name = 'comments/edit.html'
    fields = ['body']
    login_url = "/accounts/login/"

    def get_context_data(self, **kwargs):

        # 禁止编辑已删除的comment
        if self.object.is_deleted:
            raise PermissionDenied

        # 初始化旧正文
        context = super().get_context_data(**kwargs)
        ini = {'body': self.object.body}
        comment_form = CommentForm(initial=ini)
        data = {
            'comment_form': comment_form
        }
        context.update(data)
        return context

    def get_queryset(self):
        """获取 models"""
        queryset = Comment.objects.all()
        return queryset

    def form_valid(self, form):
        """鉴权"""
        if self.request.user != self.object.user and not self.request.user.is_staff:
            raise PermissionDenied
        return super(CommentUpdateView, self).form_valid(form)

    def get_success_url(self):
        """获取重定向url"""
        obj = self.get_object()
        redirect_url = obj.content_object.get_absolute_url() + '#F' + str(obj.id)
        return redirect_url

    def post(self, request, *args, **kwargs):
        # 暂时用这种方法来检查空值，需优化
        if request.POST['body'] == '':
            self.get(request, *args, **kwargs)
        return super(CommentUpdateView, self).post(request, *args, **kwargs)


@login_required(login_url='/accounts/login')
def comment_soft_delete(request):
    """
    软删除回复
    本人及管理员可操作
    """
    comment_id = request.GET.get('comment_id')

    # get model
    comment = get_object_or_404(Comment, id=comment_id)

    # 鉴权
    if request.user != comment.user and not request.user.is_staff:
        raise PermissionDenied

    # 添加删除标记
    if request.user.is_staff:
        comment.is_deleted_by_staff = True
    comment.is_deleted = True
    comment.save()

    redirect_url = comment.content_object.get_absolute_url() + '#F' + str(comment.id)
    return redirect(redirect_url)


class CommentCreateView(LoginRequiredMixin, CreateView):
    """
    发布博文、读书、vlog 的新评论的视图
    可处理get或post请求
    model设计问题导致代码臃肿
    """
    login_url = "/accounts/login"
    fields = [
        'body',
    ]

    def get_article(self, request, article_id):
        """
        获取: 回复的文章种类、绑定的评论表单
        """
        if request.POST['article_type'] == 'article':
            article = get_object_or_404(ArticlesPost, id=article_id)
        elif request.POST['article_type'] == 'readbook':
            article = get_object_or_404(ReadBook, id=article_id)
        else:
            article = get_object_or_404(Vlog, id=article_id)
        return article

    def get(self, request, *args, **kwargs):
        """
        处理get请求
        """
        article_id = kwargs.get('article_id')
        node_id = kwargs.get('node_id')
        article_type = kwargs.get('article_type')

        comment_form = CommentForm()
        comment = Comment.objects.get(id=node_id)

        template = 'comments/reply_post_comment.html'

        return render(
            request,
            template,
            {'comment_form': comment_form,
             'article_id': article_id,
             'node_id': node_id,
             'comment': comment,
             'article_type': article_type,
             }
        )

    def post(self, request, *args, **kwargs):
        """
        处理post请求
        """
        article = self.get_article(request, self.kwargs.get('article_id'))
        comment_form = CommentForm(request.POST)

        # 暂时用这种方法来检查空值，需优化
        if request.POST['body'] == '':
            return redirect(article)

        # 创建新评论
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            article_type = request.POST['article_type']

            # 对二级评论，赋值root节点的id
            if self.kwargs.get('node_id'):
                node_id = kwargs.get('node_id')

                # 判断回复属于博文、读书或视频
                # 并赋值父级评论
                parent_comment = Comment.objects.get(id=node_id)
                new_comment.parent_id = parent_comment.get_root().id
                new_comment.reply_to = parent_comment.user
                new_comment.content_object = article
                new_comment.user = request.user
                new_comment.save()
                # 对不是staff的父级评论发送通知
                if not parent_comment.user.is_superuser:
                    notify.send(
                        request.user,
                        recipient=parent_comment.user,
                        verb='回复了你',
                        target=article,
                        description=article_type,
                        action_object=new_comment,
                    )
            else:
                new_comment.reply_to = None
                new_comment.content_object = article
                new_comment.user = request.user
                new_comment.save()

            # 给staff发送通知
            if not request.user.is_staff:
                notify.send(
                    request.user,
                    recipient=User.objects.filter(is_staff=1),
                    verb='回复了你',
                    target=article,
                    description=article_type,
                    action_object=new_comment,
                )

            # 给博主发送通知邮件
            # send_email_to_user(recipient='dusaiphoto@foxmail.com')

        # 输入不合法
        else:
            raise PermissionDenied

        redirect_url = article.get_absolute_url() + '#F' + str(new_comment.id)
        return redirect(redirect_url)

templates/comments/comment_module.html
{% load mptt_tags %}
{% load weibo_utils %}
{% load get_userinfo %}
{% load staticfiles %}

<!-- ckeditor -->
<link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/prism/css/prism.css' %}">

{#发表评论#}
{% if user.is_authenticated %}
    <div>
        <form id="comment_form"
              action="{% url 'comments:post_comment' article.id %}"
              method="post">
            {% csrf_token %}
            <div>
                <h5>
                    发表评论：
                </h5>

                <!-- ckeditor 正文 -->
                {{ comment_form.body }}

            </div>

            <input type="hidden" name="article_type" value={{ article_type }}>


            <button class="btn btn-primary mt-2" id="submit_btn" type="submit"
                    name="submit"><i class="fas fa-paper-plane"></i> 发布
            </button>
        </form>
    </div>

{% else %}
    <br/>
    <br/>
    <div style="text-align: center">
        <div>
            <h5 class="text-muted" id="weibologin">
                <a href="{% url 'account_login' %}">
                    登录
                </a>
                后回复
            </h5>
            <div style="text-align: center" class="container-fluid mb-4">
                <div>
                    <a href="/accounts/weibo/login/?process=login" class="mr-2" id="weibo_a"><i class="fab fa-weibo"
                                                                                                style="font-size: 3em; color: indianred;"></i></a>
                    <a href="/accounts/github/login/?process=login" id="github_a"><i class="fab fa-github"
                                                                                     style="font-size: 3em; color: dimgray;"></i></a>
                </div>
            </div>
        </div>
    </div>
{% endif %}


{#显示mptt层级评论#}
<br>
<br>
<h5 id="Fcomments" class="mt-4 alert alert-info">共有{{ article.comments.count }}条评论</h5>
<div>
    <div>
        {% recursetree comments %}
            <hr>
            <div class="row no-gutters">
                <div class="col-2 col-sm-1" id="F{{ node.id }}">
                    <div style="text-align: center">
                        {% get_userinfo node.user.id as userinfo %}
                        {% if node.user.socialaccount_set.all.0.get_avatar_url %}
                            <!-- 第三方头像 -->
                            <img src="{% translate_avatar_ssl node.user.socialaccount_set.all.0.get_avatar_url %}"
                                 alt="avatar"
                                    {% if node.reply_to %}
                                 style="width: 70%; border-radius: 20%"
                                    {% else %}
                                 style="width: 80%; border-radius: 20%"
                                    {% endif %}
                            >

                        {% elif userinfo.avatar %}
                            <!-- 本地头像 -->
                            {% if 'static' in userinfo.avatar.url %}
                                <img src="{{ userinfo.avatar }}"
                                     alt="avatar"
                                        {% if node.reply_to %}
                                     style="width: 70%; border-radius: 20%"
                                        {% else %}
                                     style="width: 80%; border-radius: 20%"
                                        {% endif %}
                                >
                            {% else %}
                                <img src="{{ userinfo.avatar.url }}"
                                     alt="avatar"
                                        {% if node.reply_to %}
                                     style="width: 70%; border-radius: 20%"
                                        {% else %}
                                     style="width: 80%; border-radius: 20%"
                                        {% endif %}
                                >
                            {% endif %}

                        {% else %}
                            <!-- 无头像 -->
                            <img src="{% static 'default_avatar.jpg' %}"
                                 alt="avatar"
                                    {% if node.reply_to %}
                                 style="width: 70%; border-radius: 20%"
                                    {% else %}
                                 style="width: 80%; border-radius: 20%"
                                    {% endif %}
                            >
                        {% endif %}
                    </div>
                </div>

                <div class="col-10 col-sm-11">
                    <div style="color: gray;">
                        {% if user == node.user %}
                            <i class="fas fa-user-tie" style="color: orange;"></i>
                        {% endif %}
                        {{ node.user }}
                        {% if node.user.is_superuser %}
                            <i style="color: #ff5500;">[博主]</i>
                        {% elif node.user.is_staff %}
                            <i style="color: #5897fb;">[管理员]</i>
                        {% endif %}
                        {% if node.reply_to %}
                            <i class="far fa-arrow-alt-circle-right" style="color: cornflowerblue;"></i>
                            {{ node.reply_to }}
                            {% if node.reply_to.is_superuser %}
                                <i style="color: #ff5500;">[博主]</i>
                            {% elif node.reply_to.is_staff %}
                                <i style="color: #5897fb;">[管理员]</i>
                            {% endif %}
                        {% endif %}
                    </div>

                    <!-- 正文 -->
                    {% if node.is_deleted %}
                        {% if node.is_deleted_by_staff %}
                            <div style="text-align: center;"
                                 class="alert alert-danger"
                            >
                                本回复已被 [博主] 删除
                            </div>
                        {% else %}

                            <div style="text-align: center;"
                                 class="alert alert-danger"
                            >
                                本回复已被 {{ node.user }} 删除
                            </div>
                        {% endif %}
                    {% else %}
                        <p class="mt-3 mb-1">{{ node.body|safe }}</p>
                    {% endif %}

                    <!-- 附加信息 -->
                    <div style="color: #999999;">
                        <p>{{ node.created_time|date:"Y/m/d H:i" }}
                            <a href="{% url 'comments:reply_post_comment' article.id node.id article_type %}"
                               style="color: #01a252">
                                回复
                            </a>

                            <!-- 删除/编辑 -->
                            {% if node.user == user or user.is_staff %}
                                {% if not node.is_deleted %}
                                    <a href="{% url 'comments:edit' node.id %}?article_type={{ article_type }}"
                                       style="color: lightskyblue;">
                                        编辑
                                    </a>
                                    <span style="float: right">
                                        <a href="javascript:"
                                           title="删除"
                                           onclick="confirm_delete({{ node.id }});"
                                        >
                                            <i class="far fa-trash-alt"
                                               style="color: darkred;"
                                            ></i>
                                        </a>
                                    </span>
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                    {% if not node.is_leaf_node %}
                        <div class="children">
                            {{ children }}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endrecursetree %}
    </div>
</div>


<!-- ckeditor -->
<script type="text/javascript"
        src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<script>$(".django-ckeditor-widget").removeAttr('style');</script>

<script>
    // 删除文章的函数
    confirm_delete = function (node_id) {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "当心！",
            // 正文
            content: "确认删除此回复吗？",
            shadeClose: true,
            anim: 6,
            // 点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                // 指定应当前往的 url
                location.href = "{% url 'comments:soft_delete' %}?"
                    + "comment_id=" + node_id +
                    "&" + "article_type=" + "{{ article_type }}"
            },
        })
    }
    $('#github_a').on('mouseenter', function () {
        this.index = layer.tips('以Github账号登录', this, {
            time: -1,
            maxWidth: 280,
            tips: [3, 'dimgray']
        });
    }).on('mouseleave', function () {
        layer.close(this.index);
    });

    $('#weibo_a').on('mouseenter', function () {
        this.index = layer.tips('以新浪微博账号登录', this, {
            time: -1,
            maxWidth: 280,
            tips: [3, 'indianred']
        });
    }).on('mouseleave', function () {
        layer.close(this.index);
    });

</script>

templates/comments/edit.html
{% extends 'base_with_rslider.html' %}
{% load staticfiles %}
{% block title %}编辑回复 - 杜赛的个人网站{% endblock %}
{% block content %}
    <!-- ckeditor -->
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/prism/css/prism.css' %}">

    <div>
        <form id="comment_form"
              method="post"
        >
            {% csrf_token %}
            <div class="mt-4">
                <h5>
                    编辑回复：
                </h5>
                {{ comment_form.body }}
            </div>
            <input type="hidden"
                   name="article_type"
                   value="{{ article_type }}"
            >
            <div class="mt-2 mb-4">
                <button class="btn btn-primary"
                        id="submit_btn"
                        type="submit"
                        name="submit"
                >
                    <i class="fas fa-paper-plane"></i> 更新
                </button>
                <button class="btn btn-secondary btn-sm"
                        onclick="window.history.back(); return false;"
                >
                    返回
                </button>
            </div>
        </form>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>



    <!-- ckeditor -->
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script>$(".django-ckeditor-widget").removeAttr('style');</script>

{% endblock %}

templates/comments/reply_post_comment.html
{% extends 'base_with_rslider.html' %}
{% load staticfiles %}
{% block title %}回复{{ comment.user }} - 杜赛的个人网站{% endblock %}
{% block content %}
    <!-- ckeditor -->
    <link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/prism/css/prism.css' %}">

    <div>
        <div class="mt-4">
            <h4>{{ comment.user }} 说：</h4>
            <!-- 正文 -->
            {% if comment.is_deleted %}
                {% if comment.is_deleted_by_staff %}
                    <div style="text-align: center;"
                         class="alert alert-danger"
                    >
                        本回复已被 [博主] 删除
                    </div>
                {% else %}

                    <div style="text-align: center;"
                         class="alert alert-danger"
                    >
                        本回复已被 {{ comment.user }} 删除
                    </div>
                {% endif %}
            {% else %}
                <p>{{ comment.body|safe }}</p>
            {% endif %}
        </div>
        <hr>
        <form id="comment_form"
              action="{% url 'comments:reply_post_comment' article_id node_id article_type %}"
              method="post"
        >
            {% csrf_token %}
            <div>
                <h5>
                    我的回复：
                </h5>
                <!-- ckeditor 正文 -->
                {{ comment_form.body }}

            </div>
            <input type="hidden"
                   name="article_type"
                   value="{{ article_type }}"
            >
            <div class="mt-2 mb-4">
                <button class="btn btn-primary"
                        id="submit_btn"
                        type="submit"
                        name="submit"
                >
                    <i class="fas fa-paper-plane"></i> 发布
                </button>
                <button class="btn btn-secondary btn-sm ml-2"
                        onclick="window.history.back(); return false;"
                >
                    返回
                </button>
            </div>
        </form>
        <br>
        <br>
        <br>
    </div>

    <!-- ckeditor -->
    <script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    <script>$(".django-ckeditor-widget").removeAttr('style');</script>

{% endblock %}