article/api/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'
urlpatterns = [
    # 文章列表
    url(r'^list/$', views.ArticleListAPIView.as_view(), name='list'),
    # 删改查
    url(r'^(?P<pk>\d+)/$', views.ArticleUpdateAPIView.as_view(), name='detail'),
    # 增
    url(r'^create/$', views.ArticleCreateAPIView.as_view(), name='create'),

]

article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'
urlpatterns = [
    # 文章列表
    url(r'^list/$', views.ArticlePostView.as_view(), name='article_list'),

    # 文章内容
    url(
        r'^detail/(?P<article_id>\d+)/$',
        views.article_detail,
        name='article_detail',
    ),

    # 写新文章
    url(
        r'^create/$',
        views.ArticleCreateView.as_view(),
        name='article_create',
    ),

    # 更新文章
    url(
        r'update/(?P<pk>\d+)/$',
        views.ArticleUpdateView.as_view(),
        name='article_update',
    ),
]

course/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'course'
urlpatterns = [
    path(
        '',
        views.CourseListView.as_view(),
        name='course_list',
    ),
    url(
        r'^articles-list/(?P<course_id>\d+)/$',
        views.course_articles_list,
        name='course_articles_list',
    ),
]

dusainet2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from article.views import ArticlePostView
from article.feeds import ArticlesPostRssFeed, ArticlesPostColumnRssFeed

import notifications.urls

urlpatterns = [
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    path('admin/', admin.site.urls),
    url(r'^$', ArticlePostView.as_view(), name='home'),
    path('admiration/', TemplateView.as_view(template_name='admiration.html'), name='admiration'),

    path('userinfo/', include('userinfo.urls', namespace='userinfo')),

    path('article/', include('article.urls', namespace='article')),
    url(r'comments/', include('comments.urls', namespace='comments')),
    path('album/', include('album.urls', namespace='album')),
    path('course/', include('course.urls', namespace='course')),

    path('book/', include('readbook.urls', namespace='readbook')),

    path('imagesource/', include('imagesource.urls', namespace='imagesource')),

    path('vlog/', include('vlog.urls', namespace='vlog')),

    path('aboutme/', include('aboutme.urls', namespace='aboutme')),

    path('my-notifications/', include('mynotifications.urls', namespace='my_notifications')),

    # RSS订阅
    url(r'^all/rss/$', ArticlesPostRssFeed(), name='rss'),
    path('all/rss/<int:column_id>/', ArticlesPostColumnRssFeed(), name='column_rss'),

    # haystack search
    url(r'^search/', include('haystack.urls')),

    # allauth
    path('accounts/', include('allauth.urls')),

    path('account/weibo_login_success/', TemplateView.as_view(template_name='account/weibo_login_success.html')),

    # notifications
    url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    # rest-framework login view
    url(r'^api/auth/', include('rest_framework.urls')),

    # api-article
    path('api/article/', include('article.api.urls', namespace='api_article')),

    # api-comments
    path('api/comments/', include('comments.api.urls', namespace='api_comments')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vlog/urls.py
from django.urls import path
from . import views

app_name = 'vlog'

urlpatterns = [
    path('', views.VlogListView.as_view(), name='list'),
    path('detail/<int:pk>', views.VlogDetailView.as_view(), name='detail'),
]

article/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

from course.models import Course
from comments.models import Comment

from taggit.managers import TaggableManager
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit


# Create your models here.

class ArticlesColumn(models.Model):
    """
    article栏目
    """
    title = models.CharField(max_length=100, blank=True, verbose_name='标题')
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = '栏目'

    def __str__(self):
        return self.title


class ArticlesPost(models.Model):
    """
    博客文章
    """
    author = models.ForeignKey(
        User,
        related_name='article',
        on_delete=models.CASCADE,
        verbose_name='作者',
    )

    comments = GenericRelation(Comment)

    column = models.ForeignKey(
        ArticlesColumn,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='column',
        verbose_name='栏目',
    )

    title = models.CharField(max_length=200, verbose_name='标题')

    # 教程中的标题, 若不填则自动填写
    course_title = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name='课程标题',
    )

    # 教程外键
    course = models.ForeignKey(
        Course,
        related_name='article',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name='教程',
    )

    # 博文在教程中的序号，用于给博文排序
    course_sequence = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='教程序号',
    )

    # taggit
    tags = TaggableManager(blank=True, verbose_name='标签')

    body = models.TextField(verbose_name='正文')
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0, verbose_name='浏览量')

    # 缩略图
    avatar_thumbnail = ProcessedImageField(
        upload_to='image/article/%Y%m%d',
        processors=[ResizeToFit(width=500)],
        format='JPEG',
        options={'quality': 100},
        blank=True,
        null=True,
        verbose_name='标题图',
    )

    url = models.URLField(blank=True, verbose_name='标题图url')

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = '文章'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        重写save(), 自动填写教程序号
        """
        if not self.course_title:
            self.course_title = self.title

        # 跳过更新日期
        # if not kwargs.pop('skip_updated', False):
        #     self.updated = timezone.now()

        super(ArticlesPost, self).save(*args, **kwargs)

    # 获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    # 获取文章api地址
    def get_api_url(self):
        return reverse('api_article:detail', args=[self.id])

    # 统计浏览量
    def increase_views(self):
        self.total_views += 1
        self.save(update_fields=['total_views'])

article/forms.py
from django import forms
from django.core.files.base import ContentFile
from .models import ArticlesPost
from uuslug import slugify
from urllib import request


class ArticleCreateForm(forms.ModelForm):
    """
    写新文章的表单
    """
    class Meta:
        model = ArticlesPost
        fields = [
            'title',
            'course_title',
            'column',
            'tags',
            'body',
            'url',
            'course',
            'course_sequence'
        ]

    def clean_url(self):
        """
        获取网络图片的url
        :return: url
        """
        url = self.cleaned_data['url']
        # 检查url的图片格式
        if url:
            valid_extensions = ['jpg', 'jpeg', 'png']
            extension = url.rsplit('.', 1)[1].lower()
            if extension not in valid_extensions:
                raise forms.ValidationError("图片格式必须为jpg/jpeg/png.")
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        """
        重写save(), 修改图片的名字为slug
        :return: 提交的article表单类对象
        """
        article = super(ArticleCreateForm, self).save(commit=False)
        article_url = self.cleaned_data['url']
        if article_url:
            album_name = '{0}.{1}'.format(
                slugify(article.title),
                article_url.rsplit('.', 1)[1].lower()
            )
            response = request.urlopen(article_url)
            article.avatar_thumbnail.save(
                album_name,
                ContentFile(response.read()),
                save=False
            )
        if commit:
            article.save()
        return article

article/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveUpdateDestroyAPIView,
)

from rest_framework.permissions import (
    IsAuthenticatedOrReadOnly,
    IsAdminUser,
)

from article.models import ArticlesPost
from article.api.serializers import (
    ArticleCreateUpdateSerializer,
    ArticleListSerializer,
)

from .permissions import IsOwnerOrReadOnly
from .pagination import ArticlePageNumberPagination


# Create your views here.
# 增
class ArticleCreateAPIView(CreateAPIView):
    queryset = ArticlesPost.objects.all()
    serializer_class = ArticleCreateUpdateSerializer
    permission_classes = [IsAdminUser]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


# 删改查
class ArticleUpdateAPIView(RetrieveUpdateDestroyAPIView):
    queryset = ArticlesPost.objects.all()
    serializer_class = ArticleCreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)


# 列表
class ArticleListAPIView(ListAPIView):
    serializer_class = ArticleListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'body', 'author__first_name', 'author__last_name']
    pagination_class = ArticlePageNumberPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = ArticlesPost.objects.all()
        query = self.request.GET.get("q")

        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(author__first_name__icontains=query) |
                Q(author__last_name__icontains=query)
            ).distinct()
        return queryset_list

article/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse_lazy

from .models import ArticlesPost, ArticlesColumn
from .forms import ArticleCreateForm

from course.models import Course
from comments.forms import CommentForm
from utils.utils import PaginatorMixin

from braces.views import LoginRequiredMixin, StaffuserRequiredMixin

import markdown


# Create your views here.

class ArticleMixin(PaginatorMixin):
    """
    文章Mixin
    """
    model = ArticlesPost
    context_object_name = 'articles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        columns = ArticlesColumn.objects.all()
        data = {
            'columns': columns
        }
        context.update(data)
        return context


# 文章列表
class ArticlePostView(ArticleMixin, ListView):
    template_name = 'article/article_list.html'

    def dispatch(self, request, *args, **kwargs):
        """
        init
        """
        self.column_id = self.request.GET.get('column_id')
        self.order = self.request.GET.get('order')
        self.tag = self.request.GET.get('tag')

        # call the view
        return super(ArticlePostView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        """
        获取模型数组
        :return: queryset
        """

        queryset = super(ArticlePostView, self).get_queryset()
        if self.column_id:
            queryset = queryset.filter(column=self.column_id)

        if self.order == 'total_views':
            queryset = queryset.order_by('-total_views')

        if self.tag:
            try:
                queryset = queryset.filter(tags__name__in=[self.tag])
            except:
                pass

        return queryset

    def get_context_data(self, **kwargs):
        """
        获取上下文
        :return: context
        """

        context = super(ArticlePostView, self).get_context_data(**kwargs)

        # 更新栏目信息
        if self.column_id:
            c_data = {
                'column_id': int(self.column_id),
            }
            context.update(c_data)
        # 更新排序信息
        if self.order:
            o_data = {
                'order': self.order
            }
            context.update(o_data)
        # 更新标签信息
        if self.tag:
            t_data = {
                'tag': self.tag
            }
            context.update(t_data)
        return context


def article_detail(request, article_id):
    """
    文章详情的view
    :param article_id: 文章的id
    """
    article = ArticlesPost.objects.get(id=article_id)
    article.increase_views()

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    # 传递给模板文章类型，用于评论表单区分
    article_type = 'article'

    # 评论
    comment_form = CommentForm()

    # 根据教程序号，取出教程中前一条和后一条文章
    if article.course:
        next_article = ArticlesPost.objects.filter(
            course_sequence__gt=article.course_sequence,
            course=article.course,
        ).order_by('course_sequence')

        pre_article = ArticlesPost.objects.filter(
            course_sequence__lt=article.course_sequence,
            course=article.course
        ).order_by('-course_sequence')

        if pre_article.count() > 0:
            pre_article = pre_article[0]
        else:
            pre_article = None

        if next_article.count() > 0:
            next_article = next_article[0]
        else:
            next_article = None

        course_articles = article.course.article.all().order_by('course_sequence')

        context = {'article': article,
                   'comment_form': comment_form,
                   # 生成树形评论
                   'comments': article.comments.all(),
                   'course_articles': course_articles,
                   'pre_article': pre_article,
                   'next_article': next_article,
                   'article_type': article_type,
                   'toc': md.toc,
                   }

        return render(request, 'course/article_detail.html', context=context)
    # 文章不属于任何教程
    else:
        context = {'article': article,
                   'comment_form': comment_form,
                   # 生成树形评论
                   'comments': article.comments.all(),
                   'article_type': article_type,
                   'toc': md.toc,
                   }
        return render(request, 'article/article_detail.html', context=context)


# 发表文章
class ArticleCreateView(LoginRequiredMixin,
                        StaffuserRequiredMixin,
                        ArticleMixin,
                        CreateView):
    fields = [
        'title',
        'column',
        'tags',
        'body',
        'url',
        'course',
        'course_sequence',
    ]

    login_url = "/accounts/login"
    template_name = 'article/article_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        courses = Course.objects.all()
        data = {
            'courses': courses
        }
        context.update(data)
        return context

    def post(self, request, *args, **kwargs):
        forms = ArticleCreateForm(data=request.POST)
        if forms.is_valid():
            new_article = forms.save(commit=False)
            new_article.author = self.request.user
            new_article.save()

            # Without this next line the tags won't be saved.
            forms.save_m2m()

            return redirect("article:article_list")
        return self.render_to_response({"forms": forms})


class ArticleUpdateView(LoginRequiredMixin,
                        StaffuserRequiredMixin,
                        ArticleMixin,
                        UpdateView):
    """
    更新文章
    废弃，暂用admin代替
    """
    success_url = reverse_lazy("article:article_list")
    context_object_name = 'article'
    template_name = 'article/article_create.html'
    fields = ['title', 'column', 'tags', 'body']
    login_url = "/accounts/login"

templates/article/article_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}写文章 - 杜赛的个人网站{% endblock %}
{% block content %}
    {# Markdown css #}
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.min.css' %}">
    <div class="container">
        <div class="mt-2 mb-4">
            <form action="." method="post">{% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text"
                           name="title"
                           required
                           placeholder="请输入标题.."
                           autocomplete="off"
                           class="form-control"
                    >
                </div>
                <div class="form-group">
                    <label for="course_title">教程中标题</label>
                    <input type="text"
                           name="course_title"
                           placeholder="请输入标题.."
                           autocomplete="off"
                           class="form-control"
                    >
                </div>
                <div class="form-row align-items-center">
                    <div class="col-auto my-1">
                        <label for="column">栏目</label>
                        <select name="column" class="custom-select mr-sm-2">
                            <option value="">请选择栏目..</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-auto my-1">
                        <label for="course">教程</label>
                        <select name="course" class="custom-select mr-sm-2">
                            <option value="">请选择教程..</option>
                            {% for course in courses %}
                                <option value="{{ course.id }}">{{ course.title }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-auto my-1">
                        <label for="course_sequence">教程序号</label>
                        <input type="text"
                               name="course_sequence"
                               placeholder="教程序号.."
                               autocomplete="off"
                               class="form-control"
                        >
                    </div>
                </div>

                <div class="form-group">
                    <label class="layui-form-label">标签</label>
                    <input type="text" name="tags" placeholder="标签" autocomplete="off"
                           class="form-control">
                </div>
                <div class="form-group">
                    <label for="url">标题图</label>
                    <input type="text" name="url" placeholder="请输入url" autocomplete="off"
                           class="form-control">
                </div>
                <div class="form-group">
                    <label>内容</label>
                    <div id="editormd">
                        <textarea style="display: none;" id="id_body" name="body" required></textarea>
                    </div>
                </div>
                <input type="submit" value="提交" class="btn btn-primary">
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'layui-v2.3.0/layui/layui.js' %}"></script>
    <script type="text/javascript" src="{% static 'editormd/editormd.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            editormd.emoji.path = "http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/emojis/"
            var editor = editormd("editormd", {
                width: "100%",
                height: 640,
                syncScrolling: "single",
                path: "{% static 'editormd/lib/' %}",
                emoji: true
            })
        });

        {#Markdown渲染#}
        layui.use('form', function () {
            var form = layui.form;
            form.val("editform", {
                "title": "{{ article.title }}",   // "name": "value"
                "column": "{{ article.column }}",
                "tags": "{{ article.tags.all|join:',' }}",
                "body": "{{ article.body }}",
                {% if article.avatar_thumbnail %}
                    "url": "{{ article.url }}",
                {% endif %}
                {% if article.course %}
                    "course": "{{ article.course.id }}",
                {% endif %}
            })
        });
    </script>
{% endblock %}

templates/article/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ article.title }} - 杜赛的个人网站{% endblock %}
{% block content %}



    <div class="container-fluid">
        <div class="row">

            <!-- 左目录 -->
            <div class="col-3 col-lg-2 card d-none d-md-block" id="left-sidebar">
                <div class="sidebar" id="sidebar">
                    <div class="sidebar__inner">
                        {% include 'article/slider.html' %}
                    </div>
                </div>
            </div>

            <!-- 正文 -->
            <div class="col" id="main">
                {% include 'article/detail_base.html' %}
            </div>

        </div>
    </div>

    <script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
    <script>
        $('#sidebar').stickySidebar({
            topSpacing: 0,
            bottomSpacing: 20
        });


    </script>
    <style>
        .sidebar {
            will-change: min-height;
        }

        .sidebar__inner {
            transform: translate(0, 0);
            will-change: position, transform;
        }

    </style>
{% endblock %}

templates/article/article_list.html
{% extends 'base_with_rslider.html' %}
{% load staticfiles %}
{% block title %}杜赛的个人网站{% endblock %}
{% block content %}
    <div class="">
        <!-- 栏目导航 -->
        {% include 'article/navigator.html' %}


        <!-- RSS -->
        {#            <a href="#" style="float: right;" id="add_rss">#}
        {#                <i class="layui-icon layui-icon-cellphone"#}
        {#                   onclick="_hmt.push(['_trackEvent', 'rss', 'click', '订阅'])"#}
        {#                   style="color: darkgoldenrod;"#}
        {#                ></i>#}
        {#                <span>RSS 订阅</span>#}
        {#            </a>#}


        <!-- 提示语 -->
        {% if tag %}
            <h5>
                <i class="fas fa-search"></i>
                标签 "<span style="color: red;">{{ tag }}</span>" 的相关文章如下：
            </h5>
        {% endif %}


        <!-- 列表循环 -->
        {% for article in articles %}
            <div class="card mb-2">
                <div class="row no-gutters align-items-center">
                    {% if article.avatar_thumbnail %}
                        <div class="col-4 d-none d-md-block">
                            <img src="{{ article.avatar_thumbnail.url }}"
                                 class="card-img"
                                 alt="缩略图"
                            >
                        </div>
                    {% endif %}
                    <div class="col">

                        <div class="card-body">
                            <!-- 标题 -->
                            <h4 class="mt-0">
                                <a href="{{ article.get_absolute_url }}"
                                   style="font-weight: bold; color: black;"
                                >
                                    {{ article.title }}
                                </a>
                            </h4>

                            <!-- 文章标题的栏目 -->
                            <div class="mb-2 ">
                                {% if article.column.id %}
                                    <a href="?column_id={{ article.column.id }}"
                                       role="button"
                                       class="
                                    btn
                                    btn-sm
                                    {% if article.column.title == '编程' %}
                                    btn-outline-success
                                    {% elif article.column.title == '摄影' %}
                                    btn-outline-warning
                                    {% elif article.column.title == '光学' %}
                                    btn-outline-primary
                                    {% elif article.column.title == '闲聊' %}
                                    btn-outline-secondary
                                    {% endif %}
                                    "
                                    >
                                        {{ article.column }}
                                    </a>
                                {% endif %}

                                <!-- 标签 -->
                                {% for tag in article.tags.all %}
                                    <a class="badge badge-pill badge-light"
                                       href="?tag={{ tag }}"
                                       style="color: grey;"
                                    >
                                        {{ tag }}</a>
                                {% endfor %}
                            </div>


                            <!-- 附加信息 -->
                            <p class="text-monospace mb-0" style="color: grey;">
                                <i class="fas fa-eye" style="color: lightskyblue;"></i>
                                {{ article.total_views }}
                                <i class="fas fa-comments" style="color: yellowgreen;"></i>
                                {{ article.comments.count }}
                                <i class="fas fa-clock" style="color: pink;"></i>
                                {{ article.created|date:"Y/m/d" }}
                                <!-- 教程 -->
                                {% if article.course_id %}
                                    <i class="fas fa-book" style="color: #f0c674;"></i>
                                    <a href="{% url 'course:course_articles_list' article.course_id %}"
                                       style="color: #8D8D8D;">
                                        {{ article.course.title }}
                                    </a>
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% include 'paginator.html' %}
    </div>


    {#    <script>#}
    {#        $(document).ready(function () {#}
    {#            $("#add_rss").click(function () {#}
    {#                layui.use('layer', function () {#}
    {#                    var layer = layui.layer;#}
    {#                    layer.open({#}
    {#                        type: 1,#}
    {#                        shadeClose: true,#}
    {#                        title: '订阅栏目',#}
    {#                        content: '<div class="layui-card">\n' +#}
    {#                        '    <h2 class="layui-card-header">您想订阅哪一个栏目的文章？</h2>\n' +#}
    {#                        '    <div class="layui-card-body">\n' +#}
    {#                        '        <div class="rss">\n' +#}
    {#                        '            <a href="{% url 'rss' %}" style="color: #ff5500">\n' +#}
    {#                        '                <i class="layui-icon layui-icon-triangle-r"></i>综合</a>\n' +#}
    {#                        '        </div>\n' +#}
    {#                        '        {% for column in columns %}\n'+#}
    {#                            '            <div class="column_rss">\n'+#}
    {#                            '                <a href="{% url 'column_rss' column.id %}" style="color: #01a252">\n'#}
    {#                            +#}
    {#                            '                    <i class="layui-icon layui-icon-triangle-r"></i>{{ column.title }}</a>\n'#}
    {#                            +#}
    {#                            '            </div>\n'+#}
    {#                            '        {% endfor %}\n' +#}
    {#                        '    </div>\n' +#}
    {#                        '</div>' //这里content是一个普通的String#}
    {#                    });#}
    {#layer.msg('hello');#}
    {#                });#}
    {##}
    {#            });#}
    {##}
    {##}
    {#        });#}
    {#    </script>#}

    {#    <style>#}
    {#        a:hover {#}
    {#            color: #01a252;#}
    {#        }#}
    {#    </style>#}

{% endblock %}

templates/article/rss_base.html
<div class="layui-card">
    <h2 class="layui-card-header">您想订阅哪一个栏目的文章？</h2>
    <div class="layui-card-body">
        <div class="rss">
            <a href="{% url 'rss' %}" style="color: #ff5500">
                <i class="layui-icon layui-icon-triangle-r"></i>综合</a>
        </div>
        {% for column in columns %}
            <div class="column_rss">
                <a href="{% url 'column_rss' column.id %}" style="color: #01a252">
                    <i class="layui-icon layui-icon-triangle-r"></i>{{ column.title }}</a>
            </div>
        {% endfor %}
    </div>
</div>

templates/article/slider.html
{% load staticfiles %}
<div class="card-body" style="padding: 10px 0 0 0;">

    <div id="sidebar" style="overflow: hidden">
        <div class="markdown-body editormd-preview-container" id="custom-toc-container">
            {{ toc|safe }}
        </div>
    </div>
</div>
<style>
    #sidebar a {
        color: #b8b8b8;
    }

    #sidebar ul {
        list-style-type: none;
    }

    #sidebar div div > ul {
        padding-left: 0;
    }

    #sidebar div div ul ul {
        padding-left: 1em;
    }
</style>